### ISSUE TITLE
Rotation center has no effect

### ISSUE THREAD

**Issue by mocialov** [cduck/drawsvg#100]
`transform = 'rotate(angle,cx=0,cy=0)'` angle counts clockwise in degrees. cx/cy are the center of rotation.

Does not seem to produce any visible changes. Rectangles are drawn without any rotation. Using conda with drawsvg==2.1.1 and python 3.8.13

**Comment by mocialov** [comment]
My bad. `cx` and `cy` keywords do not need to be specified, just write e.g. `rotate(180,10,20)`

**Comment by cduck** [comment]
I'm glad you fixed it!

For future reference, note that SVG attributes like `transform` do not act like Python functions.  I've found [Mozilla's SVG documentation](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform) to be the best reference.
