### ISSUE TITLE
Import SVG?

### ISSUE THREAD

**Issue by rymurr** [cduck/drawsvg#109]
Hi I have a use case where I would like to import an existing svg then add more elements to it using `drawsvg` is that possible? Is there an example for how to do that?

**Comment by cduck** [comment]
Modifying an existing SVG is not an intended use case of drawsvg.  This is hard for library to do in a robust way.

I suggest you either:
- Look into `drawsvg.Raw` (to inject arbitrary SVG text into the drawing) or
- Use an XML parsing library to merge your existing SVG with the output of `d.as_svg()`.
