### ISSUE TITLE
Editing position of drawing elements

### ISSUE THREAD

**Issue by jimmychiuSV** [cduck/drawSvg#12]
Hi, is it possible to modify the member variables for the position of a DrawingBasicElement (such as Rectangle) to move the element instead of having to re-create the element? 

For example:
`d = draw.Drawing(640, 480)`
`d.append(draw.Rectangle(0, 0, 50, 100, fill='#fff'))`

and then move the origin of the Rectangle to (50, 75), equivalent to deleting the element and re-drawing 
`d.append(draw.Rectangle(50, 75, 50, 100, fill='#fff'))`

**Comment by cduck** [comment]
This is possible but I would not recommend it.  If you want to do this, update values in the `.args` dictionary.  Most types write their SVG attributes to `.args`.

```
r = draw.Rectangle(...)
d.append(r)
d.saveSvg(...)

# Move rectangle
r.args['x'] = ...
d.saveSvg(...)
```
