### ISSUE TITLE
How to zoom?

### ISSUE THREAD

**Issue by snarb** [cduck/drawSvg#14]
Thanks for great work. I am trying to do something like crop part of svg and zoom to the full picture , I think this is one of natural svg operations.

As far as I understand I can implement crop with help of  clip_path with rectangle as clip figure, but how to zoom the picture that I get to the original drawing size? 

Here is my play code that generates random points and trying to crop and zoom with no luck:

```python
import drawSvg as draw
import random
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import math

GRID_SIZE = 32
PTS_TO_GEN = 33

coloursIdsToColNames = {0:'black', 1:'white', 2:'blue', 3:'red', 4:'green', 5:'gray', 6:'olive', 7:'purple', 8:'tan', 9:'tomato'}

def gen_img(imW, imH, cropSize):
    curDrawing1 = draw.Drawing(imW, imH)
    curDrawing2 = draw.Drawing(imW, imH)
    cclip = draw.ClipPath()
    cclip.append(draw.Rectangle(cropSize[0], cropSize[1], cropSize[2], cropSize[3]))

    for i in range(PTS_TO_GEN):
        curCol = random.randint(0, 9)
        curColName = coloursIdsToColNames[curCol]
        cx = random.randint(0, imW)
        cy = random.randint(0, imH)

        curDrawing1.append(draw.Rectangle(cx, cy, 1, 1, fill=curColName))
        curDrawing2.append(draw.Rectangle(cx, cy, 1, 1, fill=curColName, clip_path = cclip))
    return curDrawing1, curDrawing2

def gen_couple():
    random.seed(0)
    imW = 32
    imH =  32

    cropX = 0
    cropY = 0
    cropW = 16
    cropH = 16

    curDrawing1, curDrawing2  = gen_img(imW, imH, [cropX, cropY, cropW, cropH])

    # curDrawing2.setRenderSize(16)  - Not working
    curDrawing2.savePng('scaled.png')
    curDrawing2.saveSvg('scaled.svg')

gen_couple()
```

**Comment by cduck** [comment]
I seems like what you want is to set the SVG viewport to the 16x16 unit area of the image.  See [this introduction to SVG viewports](https://webdesign.tutsplus.com/tutorials/svg-viewport-and-viewbox-for-beginners--cms-30844).

In drawSvg, you can set the viewport size and origin when creating a drawing:
```python
draw.Drawing(width, height, origin=(x, y))
```

So for your example, use `cropSize` to define the viewport:
```python
curDrawing1 = draw.Drawing(cropSize[2], cropSize[3], 
                           origin=(cropSize[0], cropSize[1]))
curDrawing2 = draw.Drawing(cropSize[2], cropSize[3], 
                           origin=(cropSize[0], cropSize[1]))
```

Also, `drawing.setRenderSize(width, height)` doesn't crop the drawing.  It just scales it so the output image is the given size in pixels.

**Comment by snarb** [comment]
Thank you!

**Comment by snarb** [comment]
Why the curDrawing2.setRenderSize(100, 400).savePng('orig2.png') produces empty  figure (curDrawing2 w = 1, h = 4) and the curDrawing2.setRenderSize(300, 300).savePng('orig2.png') produces not empy
![orig2](https://user-images.githubusercontent.com/4518007/76532391-9916eb00-6487-11ea-923d-321e446077cd.png)  if this is a zoom

**Comment by cduck** [comment]
This is becuase `setRenderSize` does an aspect fit (it doesn't stretch the image if the width and height are not scaled by the same factor).  It scales the viewport to fit while perserving the aspect ratio and possibly showing extra on two sides.  If you only pass a single argument to `setRenderSize` it will select the other dimension to match.

**Comment by philipnye** [comment]
For anyone like me coming across this while using v2.0.0+, `setRenderSize` is now `set_render_size`.
