### ISSUE TITLE
Specifying z-coordinates of shapes

### ISSUE THREAD

**Issue by rothos** [cduck/drawSvg#15]
Are more recently drawn shapes always placed on top of older ones? or is it possible to specify a z-coordinate of a new shape, so that it is drawn underneath already existing shapes?

**Comment by cduck** [comment]
The current SVG specification doesn't support z-coordinates so drawSvg can't.  A drawing contains a list of elements (shapes) and later elements in this list are drawn on top of earlier elements but there are still ways to control the drawing order.

- `drawing.insert(0, shape)` will add the shape below all other shapes.
- Using groups to specify multiple z-layers:
    ```python
    import drawSvg as draw
    d = draw.Drawing(100, 100)

    # Create several z-layers
    g_bottom = draw.Group()
    g_middle = draw.Group()
    g_top = draw.Group()
    d.extend([g_bottom, g_middle, g_top])
    
    g_top.append(shape_top)  # Draw a shape
    g_bottom.append(shape_bottom)  # Draw under the first shape
    g_bottom.append(shape_bottom2)  # Draw under the first shape, over the second
    ...
    ```

**Comment by rothos** [comment]
Thank you for the helpful response
