### ISSUE TITLE
How to embed a base64 encoded image?

### ISSUE THREAD

**Issue by xenide** [cduck/drawSvg#27]
I'm trying to insert a background image (from an existing svg file). 

The element itself is something like this (saved as the variable `content`)
`<g id="surface1">
<use xlink:href="#image5" transform="matrix(0.24,0,0,0.24,0,0)"/>
</g>`

The definition is something like this (saved as the variable `blob`)

`<image id="image5" width="5334" height="4267" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAFNYAABCrC .... </> `

I attempted to create the element like this

`rawElement = draw.Raw(content=content, defs=('image5', blob))` 

But I'm getting a 

`TypeError: No tag with id="image5" found.`

Any tips on how to make it work?

**Comment by cduck** [comment]
Don't use `Raw`.  It's a special class for inserting raw XML code directly into the resulting SVG.  You are embedding an image so use `draw.Image` like this:
```python
...
d.append(draw.Image(-50, -50, 100, 100,  # x, y, width, height
                    'data:image/png;base64,...'))
...
```

**Comment by xenide** [comment]
Yes that works now. Thanks very much!
