### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by Asuranceturix** [cduck/drawSvg#30]
Is there any way to align text to the right, so that the coordinates given to drawSvg.Text correspond to the right margin of the text rather than the left? What about center? Thanks!

**Comment by cduck** [comment]
Yes.  For this kind of question, check the SVG 1.1 supported attributes (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute).  For text alignment, use `text-anchor` (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor): `Text(..., text_anchor='end')`.  This info should probably be added to the doc strings and README.

**Comment by Asuranceturix** [comment]
Thank you very much, I had tried 'center' and 'right' to no avail, it never occurred to me to check that SVG calls them differently. Sorry for not RTFM'ing before. :)
