### ISSUE TITLE
Support for pattern def

### ISSUE THREAD

**Issue by xenide** [cduck/drawSvg#31]
Are you intending to add support for patterns, to be included in the definition? 

An example

```
<pattern id="pattern-chevron" x="0" y="0" width="15" height="15" patternUnits="userSpaceOnUse">
  <path d="M8 2.156l-1.406 1.438-6.594 6.563v5.688l.125-.125 7.875-7.906 8 8v-5.625l-6.594-6.594-1.406-1.438z" />
</pattern>
```

**Comment by cduck** [comment]
This would be great to add.  Would you like to implement support for the pattern tag?  The pull request would be similar to https://github.com/cduck/drawSvg/pull/13.

**Comment by xenide** [comment]
Alright lemme try
