### ISSUE TITLE
Save svg animation from frames?

### ISSUE THREAD

**Issue by youssefavx** [cduck/drawSvg#32]
Hey! Thanks for making this amazing package. I'm trying to save an SVG animation from animation frames, but am not sure how to go about it. This is what I have so far:

```
import webcolors
import drawSvg as draw

def make_gradient(rectangles=3, width=500, height=200):
    d = draw.Drawing(width, height, displayInline=False)
    rectanglewidths = width / rectangles
    rgb_max_value = 255
    gradient_color_values = find_n_equidistant(rectangles,range(rgb_max_value))
    rectangles = range(1, rectangles+1)

    rectangle_position = 0

    for rectangle, color in zip(rectangles, gradient_color_values):

        rectangle = draw.Rectangle(rectangle_position,0,rectanglewidths,height, fill=webcolors.rgb_to_hex((color, color, color)))
        d.append(rectangle)
        rectangle_position+=rectanglewidths
    d.rasterize()
    return d

def draw_frame(t):
    d = make_gradient(t)
    return d

with draw.animate_jupyter(draw_frame, delay=0.1) as anim:

    for i in range(1,30):
        anim.draw_frame(i)

#anim.saveSvg('animated.svg')  # Save to file
```

This works in my jupyter notebook as an svg animation but when I try that last line, I get the error `AttributeError: 'Animation' object has no attribute 'saveSvg'`

Would love any help whatsoever!

**Comment by cduck** [comment]
The SVG file format doesn't support frame-by-frame animation.  To save your animation, replace `draw.animate_jupyter(...)` with `draw.animate_video` (see [the example](https://github.com/cduck/drawSvg#animation-with-python)).

Creating an animated SVG file requires a [different strategy](https://github.com/cduck/drawSvg#animation-with-the-svg-animate-tag).
