### ISSUE TITLE
"in" property for FilterItems

### ISSUE THREAD

**Issue by tylergrinn** [cduck/drawSvg#33]
How do you specify the "in" property in a FilterItem?

```py
cloudFilter.append(drawSVG.FilterItem("feBlend", mode="screen", in="blue", in2="wispyCloud"))
```

This snippet won't work because "in" is a reserved keyword.

It would be nice to be able to prepend any property with 'svg' like `svgIn="blue"` which could be removed while processing.

**Comment by cduck** [comment]
This is possible by adding an underscore suffix: `in_=...`.  Alternatively, using keyword argument expansion: `**{'in': ...}`.
