### ISSUE TITLE
gradient stop animation

### ISSUE THREAD

**Issue by LittleLeonie** [cduck/drawSvg#36]
am i missing something or is these as it stands no way to add an animation to a gradient stop?

**Comment by sleoh** [comment]
closed because i found the `otherElem` parameter of the `Animate()` class.

**Comment by cduck** [comment]
Glad you solved it.  Was the issue that you couldn't do something like this?
```python
gradient = ...
stop = gradient.addStop(...)  # addStop doesn't return anything currently.
stop.appendAnim(...)
```

Can you share how you did it using the `otherElem` parameter?

**Comment by sleoh** [comment]
What was exactly what i tried yea. The `otherElem` parameter sets the `xlink:href` attribute of the `<animate>` element, if you give the stop an id, by using the `id` parameter of the addStop() method, you can use that given `id` as the value for the `otherElem` parameter.

```py
gradient = ...
gradient.addStop(id="stop", ...)
gradient.appendAnim(Animate(otherElem="#stop", ...))
```

**Comment by cduck** [comment]
Thanks.  I'll consider this a bug with the package because you shouldn't be required to use manual ids like that.

I'm going to reopen this issue until I (or someone else) fixes this so the code I gave works as expected.  The `addStop` method should return the element it creates.

**Comment by sleoh** [comment]
alright, many thanks!
