### ISSUE TITLE
On the style tag

### ISSUE THREAD

**Issue by marhu98** [cduck/drawSvg#42]
As far as I understand, there is no style tag implemented (as mentioned in some other issue). However, is there a way to print a line that is dashed? This is usually done in the style tag, but maybe there is some way to implement some sort of custom view.

**Comment by cduck** [comment]
The SVG 1.1 spec primarily supported by drawSvg doesn't support the style tag.  Instead normal XML attributes are used.  See the [`stroke-dasharray` documentation](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray).

To make a dashed line (or path):
```python
d.append(draw.Lines(0, 0, 20, 20, stroke_width=0.1, stroke='black', stroke_dasharray='6 4'`))
```
