### ISSUE TITLE
Converting SVG with custom Fonts to PNG

### ISSUE THREAD

**Issue by workingxx92** [cduck/drawSvg#58]

**Comment by cduck** [comment]
Can you provide more details about the issue?  The [CairoSVG](https://github.com/Kozea/CairoSVG/) library used for PNG output and I don't believe CairoSVG supports the SVG 2 spec including the `<style>` tag that you may be using for custom fonts.

**Comment by cduck** [comment]
Closing as stale.  Please reopen if you have more details about what you are trying to do.
