### ISSUE TITLE
Ellipse and elliptical arc

### ISSUE THREAD

**Issue by SL-prog** [cduck/drawSvg#6]
How can I draw ellipse or elliptical arc?
Is it possible to fill complex figure (composed by multiple elements like Lines and ArcLines)?
I want for example to fill a figure composed by 4 elleptical arcs.

**Comment by cduck** [comment]
You can use SVG Paths to draw any of these.  See https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#Arcs to learn about drawing elliptical arcs in SVG Paths.

In `drawSvg`, use the `drawSvg.Path` object to create a path.  Here is an example:

```python
import drawSvg as draw
d = draw.Drawing(320, 320, origin=(0,-320))

# Create the example path from
# https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#Arcs
p = draw.Path(stroke_width=2, stroke='black',
              fill='green', fill_opacity=0.5)
p.M(10, -315)  # Move the start point
p.L(110, -215)  # Add a line
p.A(30, 50, 0, 0, 1, 162.55, -162.45)  # Add an arc
p.L(172.55, -152.45)  # Add a line
p.A(30, 50, -45, 0, 1, 215.1, -109.9)  # Add an arc
p.L(315, -10)  # Add a line
d.append(p)

d  # Display in iPython notebook
```

![example](https://user-images.githubusercontent.com/2476062/59804245-44ba5280-92dd-11e9-821d-42d416d6801f.png)

**Comment by SL-prog** [comment]
Very interesting, thank you very much!
