### ISSUE TITLE
examples of changing font?

### ISSUE THREAD

**Issue by angryseptagon** [cduck/drawsvg#77]
Hi,
I am having a great time using your library to make graphics that I would like to print. but I am hitting a roadblock

It is unclear to me how I would change fonts using this library. is there even a way to add or import fonts? not sure if this is just a noob question but some examples or reference to some documentation would be nice.

**Comment by cduck** [comment]
Fonts are not well supported in SVG in general but you can depending on your use case.  If you plan to view and print the SVG from Firefox or Chrome you can use standard HTML style attributes to set the font (but this won't work when drawSvg saves to PNG).

**Comment by cduck** [comment]
This is now supported: https://github.com/cduck/drawsvg#embed-custom-fonts
```python
import drawsvg as draw

d = draw.Drawing(400, 100, origin='center')
d.embed_google_font('Permanent Marker', text=set('Text with custom font'))

d.append(draw.Text('Text with custom font', 35, 0, 0, center=True,
                   font_family='Permanent Marker', font_style='italic'))

d.save_svg('font.svg')
d  # Custom fonts work in most browsers but not in rasterize(), save_png(), or save_video()
```

[![Example output image](https://raw.githubusercontent.com/cduck/drawsvg/master/examples/font.svg?sanitize=true)](https://github.com/cduck/drawsvg/blob/master/examples/font.svg)

My comment from last year still holds in general but this should work when viewing (or printing) the SVG in a modern web browser.
